### ISSUE TITLE
no "all.txt" in test folder.

### ISSUE THREAD

**Issue by gedw99** [MikkelHJuul/ld#3]
any chance you can ad this file ? It seems to be test data for the Feature proto.

cool project, and interesting approach. Would like to play with it.

**Comment by MikkelHJuul** [comment]
Hi gedw99 I'll do some rewriting of the test. Add readme etc. Then I will include a smaller test data set.  (all.txt is 2Gib). In the meantime you can sign up and download the data yourself, go to: https://dmigw.govcloud.dk/v2/lightningdata/api, and follow the sign up process,  then download via https://dmigw.govcloud.dk/v2/lightningdata/bulk/all.zip?api-key=<your-key>

**Comment by MikkelHJuul** [comment]
Hello again!

I added a lot of stuff today!

I added a file yesterday and some query examples
I have also added a client that serves as a shell for the database (scratch container), it implements the RPCs with protoreflection via github.com/jhump/protoreflect
this means you can deserialize a given bytes-message by giving the client the protofile.

I still need to write some documentation, and the client probably have some bugs, but you could give it a spin

I don't have an easier way to ingest data than via the ingest.go file..

or maybe via the docker images
```shell
docker run [--network host|-p 5236:5236] -d --rm mjuul/ld:0.1.2
docker run [--network host] -it mjuul/ld-client:0.1.2
```
 then in the shell of `ld-client` you could load non-proto values (or proto-values if you add a protofile to the container and serialize via JSON)
using somethign like 
```shell
for x in `seq 0 1000`; do 
   ld-client set $x $x
done
```
then you could query it via keys and keyRanges, do deletes etc. 
example:
```shell
ld-client » get 1
key:"1"  value:"1"
ld-client » get 123
key:"123"  value:"123"
ld-client » get-range --from 123 --to 124
key:"124"  value:"124"
key:"123"  value:"123"
received messages: 2
ld-client » get-range --from 90 --to 91
key:"900"  value:"900"
key:"90"  value:"90"
key:"901"  value:"901"
key:"902"  value:"902"
key:"904"  value:"904"
key:"903"  value:"903"
key:"906"  value:"906"
key:"905"  value:"905"
key:"907"  value:"907"
key:"908"  value:"908"
key:"91"  value:"91"
key:"909"  value:"909"
received messages: 12
ld-client » get-range --prefix 80
key:"800"  value:"800"
key:"80"  value:"80"
key:"804"  value:"804"
key:"801"  value:"801"
key:"802"  value:"802"
key:"806"  value:"806"
key:"803"  value:"803"
key:"805"  value:"805"
key:"807"  value:"807"
key:"808"  value:"808"
key:"809"  value:"809"
received messages: 11
```

**Comment by MikkelHJuul** [comment]
@gedw99 - Does the resolution aptly solve your issue?

**Comment by gedw99** [comment]
thanks ! Will kick the tires

BTW you can use this https://github.com/maxence-charriere/go-app, instead of https://github.com/MikkelHJuul/app.
It works really well.

**Comment by MikkelHJuul** [comment]
@gedw99 Great! Thanks for the hint, I don't remember when I looked at that project. github is an eager fork'er :)

I will close this issue
